// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiYS9bmtKgrIBPcFYqPvJp_NpO5yrQ3hU',
    appId: '1:384083373114:web:4f04b063f9808cda76d903',
    messagingSenderId: '384083373114',
    projectId: 'jobspot-142c3',
    authDomain: 'jobspot-142c3.firebaseapp.com',
    storageBucket: 'jobspot-142c3.firebasestorage.app',
    measurementId: 'G-G6VX4T3Q3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPj4Egs50r08ObCt4R5cIanheyGTw4grc',
    appId: '1:384083373114:android:c40ffd153a8891e076d903',
    messagingSenderId: '384083373114',
    projectId: 'jobspot-142c3',
    storageBucket: 'jobspot-142c3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiYS9bmtKgrIBPcFYqPvJp_NpO5yrQ3hU',
    appId: '1:384083373114:web:585766155b82ab9d76d903',
    messagingSenderId: '384083373114',
    projectId: 'jobspot-142c3',
    authDomain: 'jobspot-142c3.firebaseapp.com',
    storageBucket: 'jobspot-142c3.firebasestorage.app',
    measurementId: 'G-2KCFEBDMSK',
  );
}
